name: sempro
channels:
  - defaults
  - conda-forge
  - pytorch
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - blas=1.0=openblas
  - brotlicffi=1.1.0.0=py311h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - certifi=2025.10.5=py311hca03da5_0
  - cffi=2.0.0=py311h73c2a22_1
  - charset-normalizer=3.4.4=py311hca03da5_0
  - expat=2.7.3=h982b769_0
  - filelock=3.20.0=py311hca03da5_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py311h5c1b81f_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=py311hca03da5_0
  - jinja2=3.1.6=py311hca03da5_0
  - joblib=1.5.2=py311hca03da5_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libjpeg-turbo=3.1.2=hc919400_0
  - libopenblas=0.3.30=hf2bb037_2
  - libpng=1.6.50=h280e0eb_1
  - libsqlite=3.51.0=h8adb53f_0
  - libtiff=4.7.0=hfce79cd_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.5=h4a912ad_0
  - markupsafe=3.0.2=py311h80987f9_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py311hca03da5_0
  - ncurses=6.5=hee39554_0
  - networkx=3.5=py311hca03da5_0
  - numpy=1.26.4=py311h901140f_1
  - numpy-base=1.26.4=py311hae06d03_1
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.6.0=h5503f6c_0
  - pandas=2.3.3=py311hdb8e4fa_1
  - pillow=11.3.0=py311h1f9957d_3
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pycparser=2.23=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_1
  - python=3.11.0=h3ba56d0_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytorch=2.2.2=py3.11_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h80987f9_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py311hca03da5_1
  - scikit-learn=1.7.2=py311hc6ded6b_0
  - scipy=1.16.3=py311h08a1045_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hab6afd1_0
  - sympy=1.14.0=py311hca03da5_0
  - threadpoolctl=3.5.0=py311hb6e6a13_0
  - tk=8.6.15=hcd8a7d5_0
  - torchvision=0.17.2=py311_cpu
  - typing_extensions=4.15.0=py311hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py311hca03da5_0
  - wheel=0.45.1=py311hca03da5_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/miniconda3/envs/sempro
