training:
  device: cuda
  epochs: 30               # set 30 IS DEFAULT! use --epochs N as arg when running script to change!
  learning_rate: 0.001
  weight_decay: 0.0001
  patience: 5             # maybe set to 5 with current results
  min_delta: 0.0001       # 0.0001?


# look into two stage stopping
# use adam!
